name: Extract Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Debug files
      run: ls -R

    - name: Unzip project
      run: unzip *.zip -d extracted

    - name: Move files to root
      run: |
        mv extracted/* .
        rm -rf extracted *.zip

    - name: Commit extracted files
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Extracted project files" || echo "No changes"
        git push
