#!/bin/bash

echo "=== BEFORE ==="
ls -R

folder=${1:-$(ls -d */ | grep -vE '^(\.git|\.github)/' | head -n 1)}

echo "Using folder: $folder"

if [ -z "$folder" ]; then
  echo "No folder found"
  exit 0
fi

mv "$folder"* .
mv "$folder".* . 2>/dev/null || true
rm -rf "$folder"

rm -rf .gradle
rm -rf */.gradle

echo "=== AFTER ==="
ls -R
